### ISSUE TITLE
Console is spammy when compiling

### ISSUE THREAD

**Issue by rasmusolle** [123DMWM/ProCraft#11]
For some reason the Console spams stuff when I compile the source

**Comment by 123DMWM** [comment]
Visual Studio console? It's probably just showing all the "warning" which are just things without an xml comment

**Comment by rasmusolle** [comment]
the ServerGUI.exe console

**Comment by 123DMWM** [comment]
what are you building it under? debug? release?

**Comment by 123DMWM** [comment]
Assuming you built it under the debug profile, that is what's causing the spam, it's meant for debugging which usually means spamming the console with everything that is going on. Switch it to release and you will be fine.

**Comment by rasmusolle** [comment]
How can I change profiles?

**Comment by rasmusolle** [comment]
Nvm, found it.

Thank you for helping
